"""
name_clusters.py — Automatic cluster naming via Claude API.

Reads graph.json, sends each unnamed cluster to Claude with its hashtags,
top accounts, and distinctive signals. Claude returns a short name + one-sentence
description. Results are merged into cluster_names.json using the same
fingerprint system as the rest of the pipeline.

Usage:
    python3 name_clusters.py              # name all unnamed clusters
    python3 name_clusters.py --all        # re-name everything, even already-named clusters
    python3 name_clusters.py --dry-run    # print prompts without calling API

Requires ANTHROPIC_API_KEY in .env
"""

import json
import os
import sys
from pathlib import Path

import anthropic
from dotenv import load_dotenv

from db import DB_PATH

load_dotenv(override=True)

GRAPH_JSON        = DB_PATH.parent / "graph.json"
CLUSTER_NAMES_JSON = DB_PATH.parent / "cluster_names.json"

# Use Haiku — fast and cheap for structured naming tasks
MODEL = "claude-haiku-4-5"


def load_graph() -> dict:
    if not GRAPH_JSON.exists():
        raise FileNotFoundError(f"No graph.json found. Run python3 pipeline.py first.")
    with open(GRAPH_JSON, encoding="utf-8") as f:
        return json.load(f)


def load_names() -> dict:
    if not CLUSTER_NAMES_JSON.exists():
        return {"_note": "Auto-generated by name_clusters.py", "macro": {}, "sub": {}}
    with open(CLUSTER_NAMES_JSON, encoding="utf-8") as f:
        return json.load(f)


def save_names(names: dict):
    with open(CLUSTER_NAMES_JSON, "w", encoding="utf-8") as f:
        json.dump(names, f, indent=2, ensure_ascii=False)
    print(f"Saved → {CLUSTER_NAMES_JSON}")


def _fingerprint_key(tags: list[str]) -> str:
    """Same logic as analyze.py — top 5 tags sorted alphabetically, comma-joined."""
    return ",".join(sorted(tags[:5]))


def _already_named(fp_key: str, names_section: dict) -> bool:
    """Check if this fingerprint already has a name."""
    return fp_key in names_section and names_section[fp_key].get("name")


def build_prompt(cluster: dict, depth_label: str) -> str:
    """
    Build a concise prompt for Claude.
    Includes: hashtags, top accounts, sub-cluster hints if macro.
    """
    tags      = cluster.get("top_hashtags") or cluster.get("distinctive_hashtags") or []
    accounts  = cluster.get("top_accounts", [])
    size      = cluster.get("size", "?")
    density   = cluster.get("internal_density") or cluster.get("density") or 0
    label_hint = cluster.get("label_hint", "")

    accounts_str = ", ".join(f"@{a}" for a in accounts[:6])
    tags_str     = ", ".join(f"#{t}" for t in tags[:8])

    # For macro clusters, include sub-cluster hints
    sub_hints = ""
    if cluster.get("subclusters"):
        hints = []
        for s in cluster["subclusters"][:4]:
            h = s.get("label_hint") or ", ".join(f"#{t}" for t in s.get("distinctive_hashtags", [])[:2])
            hints.append(h)
        if hints:
            sub_hints = f"\nSub-communities within this cluster: {' | '.join(hints)}"

    return f"""You are naming a community cluster detected on Dutch TikTok.

Cluster type: {depth_label}
Size: {size} accounts
Internal density: {density:.0%}
Top hashtags: {tags_str}
Top accounts: {accounts_str}{sub_hints}
{"Auto-hint: " + label_hint if label_hint else ""}

This is Dutch TikTok broadly — politics, culture, humor, news, sport, religion are all present.

Return ONLY a JSON object with exactly two fields:
{{
  "name": "Short descriptive name (3-6 words, no quotes inside)",
  "description": "One sentence describing who these people are and what unites them (max 25 words)"
}}

Rules:
- The name must NOT contain hashtags or hashtag-like words (no #, no raw tag strings)
- The name should describe the community identity, not their tags
- Be specific. Use what the hashtags and accounts actually tell you. Do not invent things not in the data."""


def name_cluster(client: anthropic.Anthropic, cluster: dict, depth_label: str, dry_run: bool) -> dict | None:
    prompt = build_prompt(cluster, depth_label)

    if dry_run:
        print(f"\n--- PROMPT ({depth_label}) ---")
        print(prompt)
        return None

    try:
        response = client.messages.create(
            model=MODEL,
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.content[0].text.strip()
        # Parse JSON from response
        # Claude sometimes wraps in ```json ... ``` — strip that
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        result = json.loads(text.strip())
        return result
    except Exception as e:
        print(f"  ⚠️  API error: {e}")
        return None


def process_subclusters_recursive(
    subclusters: list,
    names: dict,
    client: anthropic.Anthropic,
    force: bool,
    dry_run: bool,
    depth: int = 1,
):
    """Recursively name all sub-clusters."""
    depth_labels = {1: "Sub-cluster (depth 1)", 2: "Sub-sub-cluster (depth 2)", 3: "Deep sub-cluster (depth 3)"}
    label = depth_labels.get(depth, f"Depth-{depth} cluster")

    for sub in subclusters:
        tags    = sub.get("distinctive_hashtags", [])
        fp_key  = _fingerprint_key(tags)
        section = names.setdefault("sub", {})

        if not force and _already_named(fp_key, section):
            hint = sub.get("label_hint", fp_key)
            print(f"  ✓ Already named: {section[fp_key]['name']} ({hint})")
        else:
            hint = sub.get("label_hint", fp_key)
            print(f"  → Naming sub: {hint} ...")
            result = name_cluster(client, sub, label, dry_run)
            if result:
                section[fp_key] = result
                print(f"    ✅ {result['name']}")

        # Recurse into children
        if sub.get("subclusters"):
            process_subclusters_recursive(
                sub["subclusters"], names, client, force, dry_run, depth + 1
            )


def run(force: bool = False, dry_run: bool = False):
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key and not dry_run:
        print("❌ ANTHROPIC_API_KEY not found in .env")
        print("   Add it: echo 'ANTHROPIC_API_KEY=sk-ant-...' >> .env")
        sys.exit(1)

    graph = load_graph()
    names = load_names()
    client = anthropic.Anthropic(api_key=api_key) if not dry_run else None

    clusters = graph.get("clusters", [])
    print(f"\nFound {len(clusters)} macro-clusters in graph.json")
    print(f"Mode: {'DRY RUN' if dry_run else 'LIVE'} | Force re-name: {force}\n")

    for c in clusters:
        tags   = c.get("top_hashtags", [])
        fp_key = _fingerprint_key(tags)
        section = names.setdefault("macro", {})

        print(f"Cluster {c['cluster_index']} — {c['size']} accounts")
        if not force and _already_named(fp_key, section):
            print(f"  ✓ Already named: {section[fp_key]['name']}")
        else:
            tags_str = ", ".join(f"#{t}" for t in tags[:5])
            print(f"  → Naming macro: {tags_str} ...")
            result = name_cluster(client, c, "Macro cluster (top level)", dry_run)
            if result:
                section[fp_key] = result
                print(f"    ✅ {result['name']}")

        # Sub-clusters
        if c.get("subclusters"):
            process_subclusters_recursive(
                c["subclusters"], names, client, force, dry_run, depth=1
            )
        print()

    if not dry_run:
        save_names(names)
        print("\nDone. Run python3 generate_viz.py to update the visualization.")
    else:
        print("\n[Dry run complete — nothing saved]")


if __name__ == "__main__":
    _force   = "--all"     in sys.argv  # re-name everything
    _dry_run = "--dry-run" in sys.argv
    run(force=_force, dry_run=_dry_run)
